# Homework 1

In [1]:
import pandas as pd

df = pd.read_excel('99_DATASET/01_Data Mining/HW_1_dataset.xlsx', engine='openpyxl',index_col = "RID").iloc[0:14]
df

       Age  Income Is_Student Credit_Rating Buy_Computer
RID
1.0   18.0    High         No        Normal           No
2.0   20.0    High         No          Good           No
3.0   35.0    High         No        Normal          Yes
4.0   53.0  Middle         No        Normal          Yes
5.0   51.0     Low        Yes        Normal          Yes
6.0   58.0     Low        Yes          Good           No
7.0   33.0     Low        Yes          Good          Yes
8.0   16.0  Middle         No        Normal           No
9.0   22.0     Low        Yes        Normal          Yes
10.0  54.0  Middle        Yes        Normal          Yes
11.0  23.0  Middle        Yes          Good          Yes
12.0  39.0  Middle         No          Good          Yes
13.0  40.0    High        Yes        Normal          Yes
14.0  57.0  Middle         No          Good           No

In [2]:
def min_max_normalize(data):
    # Calculate the minimum and maximum values of the data
    min_val = min(data)
    max_val = max(data)
    
    # Normalize each value in the data
    normalized_data = []
    for value in data:
        normalized_value = (value - min_val) / (max_val - min_val)
        normalized_data.append(normalized_value)
    
    return normalized_data

In [3]:
df['age_norm'] = min_max_normalize(df['Age'])
df

       Age  Income Is_Student Credit_Rating Buy_Computer  age_norm
RID
1.0   18.0    High         No        Normal           No  0.047619
2.0   20.0    High         No          Good           No  0.095238
3.0   35.0    High         No        Normal          Yes  0.452381
4.0   53.0  Middle         No        Normal          Yes  0.880952
5.0   51.0     Low        Yes        Normal          Yes  0.833333
6.0   58.0     Low        Yes          Good           No  1.000000
7.0   33.0     Low        Yes          Good          Yes  0.404762
8.0   16.0  Middle         No        Normal           No  0.000000
9.0   22.0     Low        Yes        Normal          Yes  0.142857
10.0  54.0  Middle        Yes        Normal          Yes  0.904762
11.0  23.0  Middle        Yes          Good          Yes  0.166667
12.0  39.0  Middle         No          Good          Yes  0.547619
13.0  40.0    High        Yes        Normal          Yes  0.571429
14.0  57.0  Middle         No          Good           No  0.976190

## Q_2

In [106]:
import numpy as np

def equal_width_binning(data, num_bins):
    # Calculate the width of each bin
    data_min = np.min(data)
#   1/10000000 aims to include max to latest bin
    data_max = np.max(data)+(1/10000000)
    bin_width = (data_max - data_min) / num_bins
    
    # Create the bins
    bins = [data_min + i * bin_width for i in range(num_bins + 1)]
    
    # Bin the data
    binned_data = np.digitize(data, bins) - 1
    
    return binned_data, bins

In [107]:
# data = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9, 10])
num_bins = 3

binned_data, bins = equal_width_binning(df['age_norm'], num_bins)

# print("Binned data:", binned_data)
print("Bin boundaries:", bins)

df['binned_data_age'] = binned_data
print(df)

Bin boundaries: [0.0, 0.3333333666666667, 0.6666667333333334, 1.0000001]
       Age  Income Is_Student Credit_Rating Buy_Computer  age_norm  \
RID
1.0   18.0    High         No        Normal           No  0.047619
2.0   20.0    High         No          Good           No  0.095238
3.0   35.0    High         No        Normal          Yes  0.452381
4.0   53.0  Middle         No        Normal          Yes  0.880952
5.0   51.0     Low        Yes        Normal          Yes  0.833333
6.0   58.0     Low        Yes          Good           No  1.000000
7.0   33.0     Low        Yes          Good          Yes  0.404762
8.0   16.0  Middle         No        Normal           No  0.000000
9.0   22.0     Low        Yes        Normal          Yes  0.142857
10.0  54.0  Middle        Yes        Normal          Yes  0.904762
11.0  23.0  Middle        Yes          Good          Yes  0.166667
12.0  39.0  Middle         No          Good          Yes  0.547619
13.0  40.0    High        Yes        Normal          Yes  0.571429
14.0  57.0  Middle         No          Good           No  0.976190

      binned_data_age
RID
1.0                 0
2.0                 0
3.0                 1
4.0                 2
5.0                 2
6.0                 2
7.0                 1
8.0                 0
9.0                 0
10.0                2
11.0                0
12.0                1
13.0                1
14.0                2

In [108]:
df

,Age,Income,Is_Student,Credit_Rating,Buy_Computer,age_norm,binned_data_age
RID,,,,,,,
1.0,18.0,High,No,Normal,No,0.047619,0
2.0,20.0,High,No,Good,No,0.095238,0
3.0,35.0,High,No,Normal,Yes,0.452381,1
4.0,53.0,Middle,No,Normal,Yes,0.880952,2
5.0,51.0,Low,Yes,Normal,Yes,0.833333,2
6.0,58.0,Low,Yes,Good,No,1.000000,2
7.0,33.0,Low,Yes,Good,Yes,0.404762,1
8.0,16.0,Middle,No,Normal,No,0.000000,0
9.0,22.0,Low,Yes,Normal,Yes,0.142857,0
10.0,54.0,Middle,Yes,Normal,Yes,0.904762,2
11.0,23.0,Middle,Yes,Good,Yes,0.166667,0
12.0,39.0,Middle,No,Good,Yes,0.547619,1
13.0,40.0,High,Yes,Normal,Yes,0.571429,1
14.0,57.0,Middle,No,Good,No,0.976190,2

In [109]:
target_class = "Buy_Computer"
attributes = ["binned_data_age", "Income","Is_Student","Credit_Rating"]

## Q_3

In [110]:
import numpy as np

def chi_square_test(data):
    # Calculate the observed frequencies for each category
    row_totals = np.sum(data, axis=1)
    col_totals = np.sum(data, axis=0)
    n = np.sum(row_totals)
    expected_frequencies = np.outer(row_totals, col_totals) / n
    observed_frequencies = data
    
    # Calculate the chi-square statistic
    chi2 = np.sum((observed_frequencies - expected_frequencies) ** 2 / expected_frequencies).sum()
    
    print("expected_frequencies")
    print(expected_frequencies)
    
    # Calculate the degrees of freedom
    df_ = (data.shape[0] - 1) * (data.shape[1] - 1)
    
    # Calculate the p-value
    p_value = 1 - stats.chi2.cdf(chi2, df_)
    
    return chi2, df_, p_value, expected_frequencies

In [111]:
import scipy.stats as stats
from scipy.stats import chi2_contingency

for attribute in attributes:
    contingency_table = pd.crosstab(df[attribute], df[target_class])
    print(str(attribute) + " --> " + str(target_class))

    
    chi2, df_, p_value, expected_frequencies = chi_square_test(contingency_table)
    # print(contingency_table)

    print("Statistic: ", chi2)
    print("p-value: ", p_value)
    print("Degrees of Freedom: ", df_)
    print("Expected Values: \n", expected_frequencies)
    print()

binned_data_age --> Buy_Computer
expected_frequencies
[[1.78571429 3.21428571]
 [1.42857143 2.57142857]
 [1.78571429 3.21428571]]
Statistic:  3.546666666666666
p-value:  0.16976615743981127
Degrees of Freedom:  2
Expected Values:
 [[1.78571429 3.21428571]
 [1.42857143 2.57142857]
 [1.78571429 3.21428571]]

Income --> Buy_Computer
expected_frequencies
[[1.42857143 2.57142857]
 [1.42857143 2.57142857]
 [2.14285714 3.85714286]]
Statistic:  0.5703703703703703
p-value:  0.7518750053142591
Degrees of Freedom:  2
Expected Values:
 [[1.42857143 2.57142857]
 [1.42857143 2.57142857]
 [2.14285714 3.85714286]]

Is_Student --> Buy_Computer
expected_frequencies
[[2.5 4.5]
 [2.5 4.5]]
Statistic:  2.8
p-value:  0.09426430684121057
Degrees of Freedom:  1
Expected Values:
 [[2.5 4.5]
 [2.5 4.5]]

Credit_Rating --> Buy_Computer
expected_frequencies
[[2.14285714 3.85714286]
 [2.85714286 5.14285714]]
Statistic:  0.9333333333333333
p-value:  0.33399825582199805
Degrees of Freedom:  1
Expected Values:
 [[2.14285714 3.85714286]
 [2.85714286 5.14285714]]

## Q_4

In [112]:
def consistency_measurement(datas):
    total = 0
    for index, data in datas.iterrows():
        if data['Yes'] > data['No']:
            total += data['No']
        else:
            total += data['Yes']
    return total

In [113]:
for attribute in attributes:
    contingency_table = pd.crosstab(df[attribute], df[target_class])
    print(str(attribute) + " --> " + str(target_class))
    Inconsistency = consistency_measurement(contingency_table)
    print("Inconsistency = " + str(Inconsistency))
    print()

binned_data_age --> Buy_Computer
Inconsistency = 4

Income --> Buy_Computer
Inconsistency = 5

Is_Student --> Buy_Computer
Inconsistency = 4

Credit_Rating --> Buy_Computer
Inconsistency = 5

## Q_5

In [114]:
def association_measurement(datas):
    total = 1
    print()
    for index, data in datas.iterrows():
        if data['Yes'] > data['No']:
            total *= data['Yes'] / (data['Yes'] + data['No'])
        else:
            total *= data['No'] / (data['Yes'] + data['No'])
        # print(total)
    # print()
    return total

In [115]:
for attribute in attributes:
    contingency_table = pd.crosstab(df[attribute], df[target_class])
    print(str(attribute) + " --> " + str(target_class))
    print(contingency_table)

    Association = association_measurement(contingency_table)
    print("Association = " + str(Association))
    print()

binned_data_age --> Buy_Computer
Buy_Computer     No  Yes
binned_data_age
0                 3    2
1                 0    4
2                 2    3

Association = 0.36

Income --> Buy_Computer
Buy_Computer  No  Yes
Income
High           2    2
Low            1    3
Middle         2    4

Association = 0.25

Is_Student --> Buy_Computer
Buy_Computer  No  Yes
Is_Student
No             4    3
Yes            1    6

Association = 0.48979591836734687

Credit_Rating --> Buy_Computer
Buy_Computer   No  Yes
Credit_Rating
Good            3    3
Normal          2    6

Association = 0.375

## Q_6

In [116]:
for attribute in attributes:
    contingency_table = pd.crosstab(df[attribute], df[target_class])
    print(contingency_table)
    print()

Buy_Computer     No  Yes
binned_data_age
0                 3    2
1                 0    4
2                 2    3

Buy_Computer  No  Yes
Income
High           2    2
Low            1    3
Middle         2    4

Buy_Computer  No  Yes
Is_Student
No             4    3
Yes            1    6

Buy_Computer   No  Yes
Credit_Rating
Good            3    3
Normal          2    6

In [117]:
def discrimination_measurement(datas):
    descrim = 1
    for column in datas.columns:
        total = 0
        dominant = 0
        for index, data in datas.iterrows():
            total += data[column]
            if dominant < data[column]:
                dominant = data[column]
        descrim *= dominant/total
    return descrim

In [118]:
for attribute in attributes:
    contingency_table = pd.crosstab(df[attribute], df[target_class])
    print(str(attribute) + " --> " + str(target_class))
    discrimination = discrimination_measurement(contingency_table)
    print("Discrimination = " + str(discrimination))
    print()

binned_data_age --> Buy_Computer
Discrimination = 0.26666666666666666

Income --> Buy_Computer
Discrimination = 0.17777777777777778

Is_Student --> Buy_Computer
Discrimination = 0.5333333333333333

Credit_Rating --> Buy_Computer
Discrimination = 0.39999999999999997

## Q_7

In [119]:
# import math


# def information_measurement(datas):
#     # Calculate the total number of samples
#     total_samples = datas.sum().sum()

#     # Calculate the entropy of the target attribute
#     target_entropy = -(datas.sum(axis=0)/total_samples * np.log2(datas.sum(axis=0)/total_samples)).sum()
#     print("target_entropy")
#     print(target_entropy)

#     # Calculate the entropy of each value of the predictor attribute
#     predictor_entropy = 0
#     for col in datas.columns:
#         col_total = datas[col].sum()
#         col_entropy = -(datas[col]/col_total * np.log2(datas[col]/col_total)).sum()
#         predictor_entropy += col_total/total_samples * col_entropy
#         print("col_entropy-" + col)
#         print(col_entropy)

#     # Calculate the information gain
#     information_gain = target_entropy - predictor_entropy
#     return information_gain

In [120]:
import math


def information_measurement(datas):
    # Calculate the total number of samples
    total_samples = datas.sum().sum()

    # Calculate the entropy of the target attribute
    target_entropy = -(datas.sum(axis=0)/total_samples * np.log2(datas.sum(axis=0)/total_samples)).sum()
    # print("target_entropy")
    # print(target_entropy)

    # Calculate the entropy of each value of the predictor attribute
    predictor_entropy = 0
    # for col in datas.columns:
    for index, data in datas.iterrows():
        # print("data")
        # print(data)
        col_total = data.sum()
        
        col_entropy = 0
        for data_ in data:
#           to avoid Nan data when log(0)
            if data_/col_total >0:
                col_entropy -= (data_/col_total * np.log2(data_/col_total))
            # print("col_entropy")
            # print(col_entropy)

        predictor_entropy += col_total/total_samples * col_entropy
    # print("predictor_entropy")
    # print(predictor_entropy)
    
    # Calculate the information gain
    information_gain = target_entropy - predictor_entropy
    return information_gain

In [121]:
for attribute in attributes:
    contingency_table = pd.crosstab(df[attribute], df[target_class])
    print(str(attribute) + " --> " + str(target_class))
    information_gain = information_measurement(contingency_table)
    print("information_gain = " + str(information_gain))
    print()

binned_data_age --> Buy_Computer
information_gain = 0.2467498197744391

Income --> Buy_Computer
information_gain = 0.029222565658954647

Is_Student --> Buy_Computer
information_gain = 0.15183550136234136

Credit_Rating --> Buy_Computer
information_gain = 0.04812703040826927